[meta]
  title = "Go Transcription Starter"
  description = "Get started using Deepgram's PreRecorded Transcription with this Go demo app"
  author = "Deepgram DX Team <devrel@deepgram.com> (https://developers.deepgram.com)"
  useCase = "prerecorded"
  language = "Go"

[build]
  command = "go get"

[config]
  sample = ".env-sample"
  output = ".env"

[post-build]
  message = "Run `go run .` to get up and running."
